// Game Constants

var IMAGE_DIR = 'views/',
	FRAME_INCREMENT = 1 / 60.0;
    GAME_WIDTH = 800,
    GAME_HEIGHT = 550,
    Z_BACKGROUND = 1,
    PLAYER_STEP_PIXEL = 2,
    Z_SHADOWS = 10,
    SCROLL_SPEED_PIXEL = 3,
    PIXEL_PER_METER = 30;
    METER_PER_PIXEL = 1 / 30.0;
    Z_CHARACTERS = 20,
    Z_GUI=99999,
    MODE = 0,
	MODE_GAME = 0,
	MODE_SHOP = 1,
	MODE_SIGNIN = 2,
	GRAVITY = 10.0,
	BARN_WIDTH = 40,
	BARN_HEIGHT = 40,
	LAND_WIDTH = 800,
	LAND_HEIGHT = 25,
	WALL_WIDTH = 25,
	WALL_HEIGHT = 550,
	SKY_WIDTH = 800,
	SKY_HEIGHT = 50,
	CANNON_WIDTH = 30,
	CANNON_HEIGHT = 30,
	MOVE_BUTTON_WIDTH = 75,
	MOVE_BUTTON_HEIGHT = 75,

	MOVE_SPEED = 1,
	AMMO_WIDTH = 30,
	AMMO_HEIGHT = 23,
    CROSSHAIR_WIDTH = 30,
    CROSSHAIR_HEIGHT = 30,
	BARN_MODE_MOVE = 0,
	BARN_MODE_FIRE = 1,
    SHOT_RADIUS = 10000,

	PARALLAX_CONSTANT = 1,

    PLAYER_COUNT = 2
	;
